enableGlobalCache: true

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard
  - code: YN0076
    level: discard
  - code: YN0007
    level: discard

nodeLinker: node-modules

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.40.cjs
